apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/local/openshift/sonar
